# Generated by Django 4.1.1 on 2022-09-12 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Education_Information',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('examinationpassed', models.CharField(max_length=30)),
                ('institute', models.CharField(max_length=30)),
                ('university', models.CharField(max_length=30)),
                ('yearofpassing', models.CharField(max_length=30)),
                ('grades', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Old_Service_History',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('organization', models.CharField(max_length=30)),
                ('jobtitle', models.CharField(max_length=30)),
                ('periodofservice', models.CharField(max_length=30)),
                ('compensation', models.CharField(max_length=30)),
                ('reasonforleaving', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Information',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Jobtitle', models.CharField(max_length=30)),
                ('dateofjoining', models.CharField(max_length=30)),
                ('worklocation', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Information',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('fathername', models.CharField(max_length=30)),
                ('fathercontact', models.CharField(max_length=30)),
                ('mothername', models.CharField(max_length=30)),
                ('mothercontact', models.CharField(max_length=30)),
                ('Spousesname', models.CharField(max_length=30)),
                ('caste', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('religions', models.CharField(max_length=30)),
                ('maritalstatus', models.CharField(max_length=30)),
                ('professionalreferences', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
