# Generated by Django 4.1.1 on 2022-09-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_information',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
